# Generated by Django 4.1rc1 on 2022-08-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_plant_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='shortname',
            new_name='short_name',
        ),
    ]
