# Generated by Django 4.1rc1 on 2022-08-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_rename_shortname_plant_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='dfdfdf', max_length=20),
        ),
    ]
