# Generated by Django 4.1rc1 on 2022-08-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_alter_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='maintenance',
            field=models.TextField(default='[None,None,None,None]'),
        ),
        migrations.AddField(
            model_name='plant',
            name='reproduce',
            field=models.IntegerField(default=0),
        ),
    ]
