# Generated by Django 4.1rc1 on 2022-08-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_plant_maintenance_plant_reproduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='posetr',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='plant',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='plantname', to='plants.tag'),
        ),
    ]
